// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTq49c8MOJjZug33fU6TDtPnyau4-PhrQ',
    appId: '1:97352955405:web:9f7792b6fc8bc0fea78744',
    messagingSenderId: '97352955405',
    projectId: 'bank-sampah-3478c',
    authDomain: 'bank-sampah-3478c.firebaseapp.com',
    storageBucket: 'bank-sampah-3478c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0aHROmpR4z6YgxZJZ0VgT__Km75LyuvY',
    appId: '1:97352955405:android:44a933ed6ca7b8c5a78744',
    messagingSenderId: '97352955405',
    projectId: 'bank-sampah-3478c',
    storageBucket: 'bank-sampah-3478c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWQ8pBKfnRkxn7wL426YBX-4NPKT55WJs',
    appId: '1:97352955405:ios:5e4634c5f4b1731ba78744',
    messagingSenderId: '97352955405',
    projectId: 'bank-sampah-3478c',
    storageBucket: 'bank-sampah-3478c.appspot.com',
    iosBundleId: 'com.example.bankSampah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWQ8pBKfnRkxn7wL426YBX-4NPKT55WJs',
    appId: '1:97352955405:ios:5afe730cfeebf2a3a78744',
    messagingSenderId: '97352955405',
    projectId: 'bank-sampah-3478c',
    storageBucket: 'bank-sampah-3478c.appspot.com',
    iosBundleId: 'com.example.bankSampah.RunnerTests',
  );
}
